---
# Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webserver
  become: true
  tasks:
    - name: webserver stop
      service: name=apache2 state=stopped
    - name: wait for 80 to become inactive
      wait_for: port=80 state=stopped

# Restart mysql
- hosts: database02
  become: true
  tasks:
    - name: database restart
      service: name=mysql state=restarted
    - wait_for: 
       port: 3306 

# Bring stack up
- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80

- hosts: loadbalancer
  become: true
  tasks:
    - name: Ensure nginx is started
      service: name=nginx state=started
    - name: Waiting for port 80 to become active 
      wait_for: port=80
